React 18
rescript-lang/rescript-react pull request #46
Opened 2022-05-18 16:09 UTC by whitchapman

Closes #34

Per @tom-sherman's instructions, I forked his `react-18` branch and added a couple of commits. I attempted to mirror the React 18.1 documentation:
- upgraded to react and react-dom 18.1
- deprecated ReactDOM.hydrate, ReactDOM.unmountComponentAtNode
- added ReactDOM.Client to encapsulate `createRoot`, `hydrateRoot`, and `Root` module

I'm happy to modify as needed and do any additional work to close #34, but I'm pretty new to ReScript (background in Clojure and OCaml) so please advise on the following:
- I do not know how to run tests correctly. Running `node test/React__test.bs.js` did not work
- Introducing the `Client` module is my attempt to mirror React 18.1 but may not be the proper way to do things in ReScript
- There is probably a much more efficient way to detect changes between the alpha and release of React 18 than hunting through documentation and javascript code.
- If someone with more experience lists the remaining work, I have some time to tackle it.

2022-05-24 16:40 UTC, jauniuseitmantis commented
maybe somebody have any updates about timeline for merging this PR?

2022-06-09 10:37 UTC, tom-sherman commented
I think these changes would be good land as a stacked diff on top of #35 (ie. after it's been merged)

@rickyvetter what do you think?

2022-07-25 17:17 UTC, whitchapman commented
I marked this ready for review for my last 2 commits. This will eventually be rebased once #35 is merged.

2022-09-25 07:42 UTC, cknitt commented
@whitchapman @tom-sherman Thank you for your work and sorry for the very long delay. I am currently trying to clean up the repo and to move the pull requests forward.

Would it be possible to have a single React 18 PR (either this one or #35) rebased on master for review? And the other one to be closed?

2022-09-25 10:39 UTC, whitchapman commented
> @whitchapman @tom-sherman Thank you for your work and sorry for the very long delay. I am currently trying to clean up the repo and to move the pull requests forward.
> 
> Would it be possible to have a single React 18 PR (either this one or #35) rebased on master for review? And the other one to be closed?

Absolutely, whatever is easier. I forked @tom-sherman 's repo, so would it be better for me to cherry pick `b254874` so that #46 is has all 5 commits? What do you think Tom?

2022-09-25 18:04 UTC, tom-sherman commented
Sounds good!

2022-09-25 18:33 UTC, whitchapman commented
Ok, I force pushed with all 5 commits -- I think I did it correctly; although, there are conflicts.

2022-09-25 22:39 UTC, whitchapman commented
@tom-sherman Since my fork is from your fork of the original repo, I think you need to sync your fork first before I can sync mine -- how did this get to be so complicated!?

2022-09-28 05:28 UTC, cknitt commented
@whitchapman Couldn't you just rebase on the lastest master (d5d9168) and force push?

2022-09-28 11:39 UTC, whitchapman commented
> 

My fork doesn't have that commit since Tom's fork doesn't have that commit. I would need to refork directly from rescript-lang and open a new PR -- definitely doable. I'll give it a go.

2022-09-28 11:42 UTC, cknitt commented
IMHO it shouldn't matter if your fork has that commit, you should be able to add the rescript-lang/rescript-react repo as a remote in your local project dir and perform a fetch, then you should have that commit locally and be able to rebase on it.

2022-09-28 12:23 UTC, whitchapman commented
Ok, @cknitt I did what you suggested which resulted in modifying the PR to remove the test changes since the `test` folder has been removed in master.

2022-09-28 12:32 UTC, cknitt commented
I think that's fine if the tests have been removed in the meantime.
Looking at the changes, is still everything there that you would expect (except for the removed tests)?

CI is still failing, you need to make some small adjustments in the V3 compatibility modules to fit the changes.

2022-09-28 12:40 UTC, whitchapman commented
Yes, my changes are as expected. It has been several months since I last looked at this, and I'm not familiar with the V3 changes. Is there a resource for the V3 changes? I can look at this later today.

2022-09-28 12:46 UTC, cknitt commented
Looking at the CI errors, I think it's just about adapting to these changes:

* ReactDOM.Experimental.root -> ReactDOM.Client.Root.t
* useTransition does not take a transitionConfig anymore

2022-09-28 15:26 UTC, cknitt requested changes

2022-09-28 15:26 UTC, cknitt commented on src/React.res
> +external useTransition: unit => (bool, (. unit => unit) => unit) = "useTransition"
Looking at the docs (https://reactjs.org/docs/hooks-reference.html#usetransition), shouldn't that rather be

```rescript
external useTransition: unit => (bool, unit => unit) = "useTransition"
```
?

2022-09-28 15:26 UTC, cknitt commented on src/React.res
> +external useSyncExternalStore: (
About `useSyncExternalStore` and `useSyncExternalStoreWithServerSnapshot`:

* The type for the subscribe function does not seem to be correct here. It should take a listener function (`unit => unit`) and return an unsubscribe function (`unit => unit`).
* Especially for `useSyncExternalStoreWithServerSnapshot`, it is rather unclear which parameter does what (getSnapshot vs. getServerSnapshot), so labeled arguments may be preferable - although we don't have that elsewhere in the bindings yet. What do you think?

I have my own versions of these bindings in a project and they look like this:

```rescript
type unsubscribe = (. unit) => unit

@module("react")
external useSyncExternalStore: (
  ~subscribe: @uncurry ((unit => unit) => unsubscribe),
  ~getSnapshot: @uncurry unit => 'state,
) => 'state = "useSyncExternalStore"

@module("react")
external useSyncExternalStoreWithServerSnapshot: (
  ~subscribe: @uncurry ((unit => unit) => unsubscribe),
  ~getSnapshot: @uncurry unit => 'state,
  ~getServerSnapshot: @uncurry unit => 'state,
) => 'state = "useSyncExternalStore"
```

The `unsubscribe` function is explicitly uncurried because I was not able to get it functioning properly otherwise. (Not sure if a separate type declaration for `unsubscribe` is warranted, probably it should just be inlined.)

2022-09-29 01:45 UTC, whitchapman commented on src/React.res
> +external useTransition: unit => (bool, (. unit => unit) => unit) = "useTransition"
Looks that way to me, but I didn't write the original.

2022-09-29 01:46 UTC, whitchapman commented on src/React.res
> +external useSyncExternalStore: (
I did not write the original, but I do like the labeled arguments.

2022-09-29 05:21 UTC, cknitt requested changes

2022-09-29 05:21 UTC, cknitt commented on src/v3/React_V3.res
>  ) => (callback<callback<unit, unit>, unit>, bool) = "useTransition"
Just noticed that this still needs to be changed to match the definition in React.res.

2022-09-29 05:34 UTC, cknitt commented
Sorry!!! Looking again at the discussion in the original PR (https://github.com/rescript-lang/rescript-react/pull/35#discussion_r839220770) and also at the TypeScript typedefs for `useTransition`, I realize my previous comment was wrong and this definition

```rescript
external useTransition: unit => (bool, (. unit => unit) => unit) = "useTransition"
```

is actually correct. Let's change it to this in both the `React` and `React_V3` modules.

I think then we are done. 🎉

```
     * The `useTransition` hook returns two values in an array.
     *
     * The first is a boolean, React’s way of informing us whether we’re waiting for the transition to finish.
     * The second is a function that takes a callback. We can use it to tell React which state we want to defer.
```

2022-09-29 08:25 UTC, cknitt approved these changes
Looks good to me! 🎉

@tom-sherman Anything to add from your part?

2022-10-01 05:56 UTC, cknitt commented
Ok, merging now. In case anything is still missing or incorrect we'll address it in separate PRs.

2022-10-01 05:56 UTC, merged